In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn as sk

In [41]:
import os

In [42]:
directory = "./jsons/"
files_only = [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

In [43]:
from pprint import pprint
pprint(files_only)

['e3a240b4df07f93529120274d2796a1a.json',
 'e04f78df44364892aa2c58634b09c837.json',
 '1122e55e8329f0d1446f38a9c34063e8.json',
 'd40c6b2d0f2858cdafcd385c02cf6958.json',
 '9cc7ba719c05d71c2b7a26caf89e0fb1.json',
 '39d00090c65d2de7f510d778bb8e29a9.json',
 'ed22c3f40d0f47a4d0a7893d8461e9ee.json',
 'e918d6bc8ecdbe93f8e952618a5f04f5.json',
 'b37b1795180ce014ae65799d8f62b71a.json',
 'a48c4c0a2ab9b1e25ceca474a185f19f.json',
 '8f326f1dca4d494e7a1b09e5949e9d4c.json',
 'd4360cb2580400bfe899d83075a16e65.json',
 '3e3ef7fd9a46df82bf08200c8153787b.json',
 '2affadc7d7ee5eacae5641a78148d628.json',
 '7d90adc634d875eec22f5181d852890e.json',
 'c17797a7630cb3c40e7cbf2cd8b1fd55.json',
 'f6487bc65cb2fcda4216e4e2c95bd399.json',
 '7a8020db267e69f2ed47bdbcd1ba5dfc.json',
 '9d10c10966190f32be47a490736fc171.json',
 '06c05d41c36c4b5727d1fc5f663806bf.json',
 '811d9f83ae443fcbd60c3588a6f10e9a.json',
 '5f6cb3fbebc1e492cd093067a2cb867a.json',
 '82fbd188c1e34ba34a8880d70c8639a9.json',
 '5bb8c72b9f28fb7a8c8937eff001b8c2.json',
 'cfebc4beed292a2b1836a8f2df25e635.json',
 '2e6f5016062e13f14816e34a4649ee0b.json',
 '85fb33f14582c54616aec708b2805a33.json',
 '73aec8cad27d5b4f9a979811f384cc2d.json',
 '8ed1dbe4d1dd584927b552259b7d83be.json',
 'df6e2b3de50ecfcc944e453544e7172c.json',
 'bf49e97a05e773766f0cccaa6ad5f95e.json',
 '18e57d6ab83cd0df85a2529347a33ac3.json',
 '804d664cf46136a8cca31d1325743804.json',
 'cfbe4b3b297b5c707801a029d2355101.json',
 '5596d3a26cae2fa4c6bb7fcd27dfa744.json',
 '1e4c7d4311e33d3f31085dd8ce642b74.json',
 '670b96af33c129121a264df0c384722e.json',
 '77f953a91b61c19a10f8033e2456c973.json',
 'b5e03642b0b16a8fa97668b0c0e6113a.json',
 'd3541dd6fec0b906ec5888f777cbc890.json',
 '5aeb9946ee82f44c5a7e65250adbbcd3.json',
 '07d9747b0de112aed000f98ff688ccad.json',
 'fbb7b11decbdd5d006f0e3285f8a5c2f.json',
 'ef3072f0f5ff0235aad0514deda0a6fd.json',
 '30987385c8f45b14422d34d7eb5d99b7.json',
 '2099bb675e00d2fa7519346f6ccdd79a.json',
 '0cac987c0b91af3a2f3f6034985312c3.json',
 'f0a9713d9805864db9e46714b8ff7aae.json',
 'e2b60150abaa4927d9b074c806ba4735.json',
 'f0ba0f2f64b2dfc9321ad5daa63168fc.json',
 '92e0f58de58756121fc4663be8bde8e5.json',
 'd2d5b93c47b9b45b24cc841827c40478.json',
 '5061b96b9a7dff95b3096ba50eb1ce6a.json',
 '050ac58017e57fa6ac5d639d163bc079.json',
 '52f246922eb4f6595649608e7f616979.json',
 'bd8500bad550cd15d25e4b8355edc075.json',
 '2baf70001e12b2826e0b261d14772bbb.json',
 '9a9e10aefbc9800d03b7339077b45702.json',
 'adaabcdb47dfc21bf5d49b28762f0398.json',
 '4ab9fcf91c643a0ff52abc0ffacc4a3d.json',
 '19b4e56753f827b55dabfdfbbd04c797.json',
 '853bb688fbc861a874c4d53f0d9b10bb.json',
 '9f110939fd01aacdf428f040f18b474b.json',
 '062442b53c224f67f17e66d8ddb3803a.json',
 'e8d8814b849cf823a1ecbbc77870fac9.json',
 '198bfe270c036dce7c9a96f009b6859c.json',
 'e2ede773d46f84b3ddaf5dec04790acd.json',
 'd19adf166dead70a20c9b0785db39310.json',
 '435a4802eea29d46196377e1ffccf0cd.json',
 'c4226137d5de2b49a08adfe90297c7b1.json',
 '0f4dec1b89606ecbf7127dbce70ff844.json',
 '79534699ab8e43b09364434195626194.json',
 'b1fc529731ee824c1154f2c84d126777.json',
 '1b8a19138cc4286fde9a8bc4281b846e.json',
 'f277f4bcf87e6d2f24558fdd886c5d47.json',
 '8f63d25e86bc8324ea6c43338e0f89ba.json',
 '811a3ccfa4284bf8cf8bd5ac20e5ae82.json',
 'eea4f42b798dfe0c22e245f6c8036780.json',
 '5dfd6244b1c40f9159a2c4b9ee970cf5.json',
 '1c761f2f200cef9f3b21f5eddc8d2e7f.json',
 '4dc8f800e88f95f94416e6567b5cd6cc.json',
 'c79870ac85a02cc64f67135533a3e65e.json',
 'a51be99b753aa31f1725dd4ada0109ab.json',
 'fd3ef35e8fece2f1b5081883b7b29302.json',
 'd13fda68a01a325a61d589d7170c05e7.json',
 '5c4eb5811ea32e1fa76e96778f896f70.json',
 'dd2880c7fab84e9f46cda09e9809be01.json',
 '3090f02739d19b6997a201dad00eb1c5.json',
 'a9534f1f3daac7e8161dfe875c2f8f31.json',
 '522a3d5e6ad8805f7fca8172f4c91030.json',
 '1370288258a3afcd8a3cbcb90a2479eb.json',
 '154e9dfae0f9a1bf9c48a393e126215d.json',
 'bd3a2933dca94852d0dc94119e29aa1d.json',
 'd07847106a7f387a82f829e75dc90219.json',
 '880d820d08a139d1930bd2aa25c8bd90.json',
 'b1ebfca463b992acfdd08139ebe8e20a.json',
 '4bb5f59fe79559e639f02f2a178d24b1.json',
 '598d81f26d923b354402245bc03cb12d.json',
 'c3cbb037eab621d9f47874ecf71db8e0.json',
 '66cd122b3b1215c0cb82fceabefdad5a.json',
 '8de19ad624810be904c93b5f181725de.json',
 '6be9954bc128450f29c9099641721a5a.json',
 'e940f0211589dcebcb38f14b14402892.json',
 'df6e22643e3f2362f843ffa0be712abe.json',
 'f0508eb58aceb34f33c48d23bddcab95.json',
 '7b0fc6b38a6d52ae4dfd773320a98077.json',
 'a28044745d421ae454a08f2f968c0130.json',
 '521994b3451f7f1103549b906c1990b8.json',
 '2600fadaeb987ff46cf3e65d28ca0fb4.json',
 '852b05a331c010bba7ce47738f6435c0.json',
 '07c17af2e9be5b266edc531ffe204ea9.json',
 '0d048546d2a3ec21c2855a443f2abdac.json',
 '3a7cbed4063226ed0215610b4b2d5c47.json',
 '029f594cb0bad128e06aead0142d1d7a.json',
 '084dc35cc18b1bca28dc8fdb5ff8e1bd.json',
 '05ddea77d4062a70905d0d52e7631e0f.json',
 '935a2a87d08e6f6aff97c560a672651f.json',
 'e448a80bb4fdecc92a617e7b51d8782b.json',
 '61031854dde1aee05f3727a7ee40302f.json',
 'dd733f0da9eb95a7327a1587fc8587ef.json',
 'e02e68cd28772765ab8473e5dffa7021.json',
 '3a2da2af19737360d5b0d1b6d946af59.json',
 '1e01424308b91a3e2fcad9e1a61f9138.json',
 'ee3e395cf35226c6eefda03745f14be9.json',
 'ccea6cee15f3c65813e9e4d4b57a39cc.json',
 'de99c21547cf724c3034fe8a913e8a94.json',
 'fc9a59f17f2927c7e1795841b9854cf1.json',
 'a113f9817eb6d5591c4fa73ef980d712.json',
 'c1a953b318df6ce54974e25449656d14.json',
 'afecd8a2d90b749c12608b2213db59c1.json',
 '99239015754996b23c272ff8aad0c170.json',
 '7670f285237487d75e80870270d5790b.json',
 'da17626798a2a54d6e0b73e4c7ef045f.json',
 'b84dc46b65f39b5a718f56bfbde83999.json',
 'e0747e7607b6b8fc65d24d4dc3607876.json',
 '3741efb562da77e8d7cbb1903837ffff.json',
 'b3d007b1cfac073318c5683524a08d6d.json',
 '7ec627445e00174c3a0fd41ef82d9ef2.json',
 'e8a8f913ac979f85fabba6ae47639d87.json',
 'a0f626d0516992dfcf4bc0fc645f1ef8.json',
 '89bc7a90076df361ada8a0b6c9adfcb1.json',
 'e68a458468a335c28a401467aceae250.json',
 '562e344b97012925facf3ea81bd23075.json',
 '71729e7f9cd257eb2e56753f2440a7c8.json',
 'ee1de842f2b2378db816318a676a0562.json',
 '5aa7c3eabf6b31f9f2292be3a367ff84.json',
 'ff43d64ad6d19c866159960e55af29d7.json',
 'c35465ae1f11433b291472fc1b6f6814.json',
 'a89bf11605e5dffbd75b962cc95a1b36.json',
 'eb006718988201c999fe54c7fa76454d.json',
 '87036235aec2028b50ae356f45034ad7.json',
 '863e2cba97e1842252eb2a340a91d6d3.json',
 '5776c3195d3ceb6c7356a211388be756.json',
 '9a9592c64cb67001325dc7a77e022ad8.json',
 'a9e2d4a2087ccd384ab2b731449f225a.json',
 'fff02dee735b070bfbbcc28390e7d6c8.json',
 'ee80bbded815dd066d2eae3d4cb0d229.json',
 'd8cb47f9c646a4f08ba29bf51f157804.json',
 '1691f2b8219fb82569be4507e0ed84e1.json',
 '69f229d00589f6f367c5ef7200bd06f9.json',
 '15026e08eb69304b6ee87244cbe06a97.json',
 'b0dd6ab19ff2dad9c5634f09f6f69c40.json',
 'b18c34861d11d3e11668aea04c89964e.json',
 '9b3152a90637b80783a42ceaf48ea75a.json',
 'fec69bcc4a08298d0b52557ac511014b.json',
 '66f81d3e84534f42a1221967ea5f16c4.json',
 '691e15831b64f738f988d7c781103054.json',
 '0ed75edca42b9f25c8029ca1d0a942d2.json',
 '7ee2707c3d95fc3ce1e0bf6c2c96c160.json',
 '235b3c4125b832ed22ddcd864aa50a41.json',
 '98e1b4bc619ca37fc0676a59174fdb87.json',
 'c6b7cd4d875bbd577506999395db51f9.json',
 'ca9dc4f40574c3b96612a078dc0e89e3.json',
 '6d45e4e3176aef0825980482c1ba0e90.json',
 '3e8b9a10970f4d4d5e794925984fee23.json',
 '6aa2b96474e0b49eeedc88511a07c801.json',
 'cfdaff34952036c795199666706bb515.json',
 '2992bb07b229ac4aa36c35f98bb8f268.json',
 '9330694f015b5fb01c138c2d3e984fe4.json',
 '8b2fee42297126aaf84670b1e84cd5e9.json',
 '7c0c4b8602fc29312da0935789e309b6.json',
 'f5aebf58388d3be0ac92ce0fee626edd.json',
 '5ff71fae2d8cea536afa5b5c5c044f98.json',
 'eef56199efe48177ead6a52287d054bc.json',
 'b9ef94cb68a9c4f8362a9d28a4352216.json',
 '3a91bcbb27400a39364dcadf1e8f2d9f.json',
 '931480c023d278127600120ec3983127.json',
 'e7be72c22cb86a2363648a74eb5b98a7.json',
 'baee7638b04505c6ec958254743653a3.json',
 '669def0c241e79bb541144db1928bc98.json',
 '3599d88bcf380f0311476204f9fa042e.json',
 'ba736f3ed45f9633f6b5c88b1d77aae6.json',
 'b8719f31d5c3fa63d1d20dba1f360b19.json',
 'd00494f060408be4a5ce5b40ccb2af75.json',
 '82abf99042e3bb8ebc7fdd2dd00769e8.json',
 '2ae2e5c2a24232472693267d81824b84.json',
 '28b1339bd6ab6def1d8a1fb6a4d4fc21.json',
 '99b5175191ff264d958795b68eee21bf.json',
 '493fe6f355ee19676e75f26f6a2fbca4.json',
 'bae0dba21dfca83ba96d5cece9149644.json',
 '88c251a24fbf9c904aa527bd54a0c174.json',
 'a07d46d130859c5a180b6c9938ac6031.json',
 '58ff7ea8972f0ea24928072796d5051d.json',
 '43aa67461151056ee7db803b5d5926e4.json',
 'e6a931c6c67a28801f1320abeb384eb0.json',
 '4cbfe215cca8f17373594117c16a1d37.json',
 '3a3f9912c7e96bd3c96e21d9de19ef78.json',
 '98333d399b44303b33194908a28a232c.json',
 '54fa53d52d021bd1692293783881ee23.json',
 'dc8df22035b5c4074797e80069e7a1df.json',
 '00b8641e6c103348c4a03175c818ede1.json',
 'c0118ac7aad9dc6a7dab5cbf70c4a1eb.json',
 'f18b79c7733b8e72e5b1670e62f881f3.json',
 'a61b9eadfa936ae4e8e4bbed359a3a4b.json',
 '0e66143d84f28d65a397ff1c32086092.json',
 '66419cdf23927603f0e9c540c630a604.json',
 'b526c1ccfc1b32431f2d2a192354de16.json',
 'eecc8700595469a7acabe38177cba87b.json',
 'e75c2d4dd9d53d842f0a71ceba2674ab.json',
 'e4ff94de4e5b6b4a70611b43451d0d8c.json',
 'b35be19300d6d61f4332a50289b730cf.json',
 '66f6001621d6eb1fff44f9c6f46ae29d.json',
 '6ffe275f7418d9f623affe2903fa75cc.json',
 '05b3714f27436e2c73f52ee61052124b.json',
 'cda25e44196ae541bd9cc21795d051d8.json',
 '6a6ee630e6cca714259ee12cbd17b631.json',
 '7e89d1af863a135875b90bbce954950d.json',
 '6e4a7459b1f97166979bbc96f03f67f8.json',
 '7b9740f923d1a7580052d77dad241262.json',
 '0f5faff053ea30d2b7427aae2437ca6c.json',
 '7ea8ab52aceaa04b8f05fc22b2c36d82.json',
 '2d1089733139803c5fd92a457bc6263c.json',
 '8cef1d88ce98c5a035078a4f3e46f2c5.json',
 '64417abccf48474d5babb91dd8899081.json',
 '5ada86833c8991bb851578bfe0822320.json',
 '5126b812a39185904c703b06561e5286.json',
 '47f1b458eb81a8edfdac4201e7493e14.json',
 'bd8b7c6d0a13142f77dcd1766eaaae89.json',
 '9a5e70c40030a01215924fb78088cc13.json',
 '083c689cb96345e8378201d43db12d10.json',
 '4819cf314df4c1f15709a45cdedd2ade.json',
 'a6a8af6eff4a42f450bde68f03d9d496.json',
 '1cadb8c0a6b7888cdc64cfeb3ef85f58.json',
 '61e4434bfc5f8bab4493022eba7edbed.json',
 'ad2936d03b847ab40c7354180aeb6d02.json',
 'a2943b82545edc96e5e1dfba672d2d36.json',
 'f81a96fc43965b8e7ace096e15920f1c.json',
 'aa332adbe266736f751558065b771b79.json',
 '40992d6c7403ca9d083e23b11c31cc8f.json',
 'f8949b45c88abce15a05b3b5103dbc65.json',
 '995ef8f8199eaa1ec2bceaace78e3870.json',
 '29daace6d5a28236a5eecd55b93b54d2.json',
 '1f68c9198c2a7a802da334e687706c59.json',
 '4bbb634b4f35a20350f69124f70251b5.json',
 'c6a9b8e8ad22632edc6b28340e29455c.json',
 'c6c845341f5e8a6e1867eb3b77f259b8.json',
 'e7a7217e61c68e81bdf2e59880c0b86e.json',
 '6ad94c0fe26bea64fe34a74294ac898e.json',
 'bd90f77ed6226f4a68443220214e5e82.json',
 '2e19c25bc03965f38eb2b27f715a3bd6.json',
 'c560d645c0d9211aa43e907bea26db9e.json',
 'a35bad76d5ff6735f4c07062e76289d6.json',
 'cbdb9d98c7929e9b85363f3c613fed81.json',
 '3885d2bd0bdf85f34e9172be8d593260.json',
 'eb0cc0f6e071912aecf7d1038ca43bfc.json',
 'eb936298883ba27e68ab820be94f0679.json',
 'c931738528cbab1cd62cd1ad531e71af.json',
 '4b3767bb543c84819b425fdeaa83a414.json',
 '98faff30fadb675c46c56a4e812de14a.json',
 '578f68738bdbae6873a68552896cb9ab.json',
 'df8819b831d18ed9e85ac57216137361.json',
 'c4ad760e4008cce0f0d0eef0420bc5d5.json',
 '4999e63c38ca0cfbefd1b6c0a00339ca.json',
 'e2b34d93fbfd2dd5c4b7d00d869d8d74.json',
 '4c3ce3e92bf33abc001f71bc51b93d51.json',
 '36e30d5f7796674ecef5435292faa9ce.json',
 'e7593c0d5d0bd22524ecdaaed9dac9d1.json',
 '0d3cad39f22493af75c7be12351cc7bf.json',
 '3a265a11f5541cbb75d74bd11e62a2b7.json',
 '12f79ef2f63b3dcf5b4dedbe2cbce545.json',
 'b686fe629cf86e2026d148354c2f6561.json',
 'fc90aac0aa79d5b28ddb42ea0f185aee.json',
 'e79c90599eb24525b246f08a38f9b180.json',
 'ff0254c15a80a46ef9462341ac3c57a7.json',
 '988192e501009ec751f883a5624bd639.json',
 '9c38404f1922cf296f00cfe9db80cd77.json',
 '68ceed89ad97038f5066551a43997bea.json',
 'c28c44b160e099f4c0a6fe009928995f.json',
 '164369ebb9f3cfff9f69194e4a418c7a.json',
 '8665d1ca9be10371791cd02782386507.json',
 'bd0d8f17db412ec199bbdad9beb18ea7.json',
 'cabc20c4de6fa45a12d097c3fd5d3ee8.json',
 'd634ba95f6b72b8df5a31132fff3dd73.json',
 '8285c5fdc4bdba9cffee9f257b4b0233.json',
 '8dae38401a1e00aac7cbae26b9566944.json',
 '1b3dfb9ce943e94a9669a3213987f252.json',
 '7ff932ee96e2d6280de5479c3f6fe595.json',
 '9cad1b02d2485d82708306db8df15917.json',
 '99ba4033f5966a8d79b904e57bffd857.json',
 'a1d402e217d45667020d4acee7a114e9.json',
 'f141852a36c8424493121b6a3f70dde5.json',
 '23e3f6ead74c9634922508ccc0b1375f.json',
 'd809dfa1c1192550cc1df2c49881e203.json',
 'd64f674c20a8ac52c480b1c631fa839c.json',
 '66f19069c3aa0d388f60fb66ac659058.json',
 '55fe0eb0c3737c933b0356de52d9d3ca.json',
 '2a39e77ca6c0181aed14b74c7ac14504.json',
 '094d7daec9d4e70fdcc6f2842f3d361a.json',
 '00eab240284c11c5ba1e78feaaf0d6b0.json',
 'a080479cf7f3ede01b90328aa96148cc.json',
 'bbee1bcdd824921b621127f9d2d58c89.json',
 'e5a934a92fb0cd1f8dc9ba45c92ec148.json',
 '5fb93ea20e4571ffbbabf7297e302032.json',
 '158551d25b47d48b8d757ad2c6c672e7.json',
 '44ee36efc4682229c836ccb0e23a823e.json',
 'a81c182d19e7bcd63eb47b82157e9f7b.json',
 'a5e6f6864e72801d0fe46de6c0cfedc4.json',
 '547febd5b93092a4d8934d03a3cff6a0.json',
 '9d5fa247a26d30052b8e9159d8352eec.json',
 'a6aef9ed2be381b7abad90be5edd8816.json',
 'b5db47137a119c16de9fc2f220b9886b.json',
 'b699d71d4f66fcf7951cc8454aada952.json',
 'f225671ca540c41680a9c3e7176823dc.json',
 '5a559b2b11d5010db59ecd25de93ae12.json',
 '2e235b6a698c8bc051ab5ec57bdc6e48.json',
 '2cf446732d1c40b04ee8f3b5d97d2f45.json',
 '0396ba16bd524c141d5d0477f9375310.json',
 'bdd7ed17f049df9010b433d72508dc52.json',
 '84d96652cdf7d1c8a034a47a1414997e.json',
 '49295ad3fc3db00ba33b4889f4ea47de.json',
 '615c5dd8fa974865f34ea2d5f96fb71c.json',
 'cf96fe17c13783bde11f6c8d6ec97b09.json',
 'cbdcf4f8d0184794bd9c0eed588671d7.json',
 'c3a40c73f34d13948ce20455a712152d.json',
 'e9dc91fb9745120bd5449c32549a9a6f.json',
 '6f574d94e86ebe26ca559b14bb23cfa1.json',
 'c4cca54e0e19d843abc94eeb2d981b3b.json',
 'ac995ed8997fbf090172265caf2c51aa.json',
 'b4da2b7cb40c0dce5ee37fd5ba604a86.json',
 'b892b453ab8ef2b45a781b85a12a930d.json',
 '134825b88f1ef78e9960a90b6e6afda6.json',
 '7b95490cb82b4b7913195eeb50cc56f7.json',
 '42b4afcd2565b6ee6f59fead52701c23.json',
 'ac63c1a6669b81c3706a68ce785205b6.json',
 '71682d21be1f6dd80596da9560f3a7bb.json',
 '1aa91bda35905a628b7ec7c104807fe7.json',
 '660f5c2be6a5b1abf6156db95e31a250.json',
 'dbcf8a49c85d39ee978ac35015355602.json',
 '0443070ab0054957d32782ca56132242.json',
 '71a21a6c5feafd8b4b6754d6f124ce51.json',
 'fa9b3f21e979a47ae6d7ced1ef9e4642.json',
 'b6122eacc12e4aff0bd70873fe66fae7.json',
 'ce500abfba203ad7b8038e76400b148c.json',
 '2fcca2771683a1eee403f3389d44867a.json',
 '5d028b6266313ece5def22d704e06618.json',
 '70e83d57a66d5cae21fa625deaa0ac5a.json',
 '71d8dc278422e3d07a369ff1fd0588f0.json',
 'cba7e8af8fd21bf82175b44c34d1dd67.json',
 '5a9007cb23ca9ac4174fdc47585eb924.json',
 'db4c0a01c06dfcfd7ebe850792ed6ca9.json',
 '268a6abf7b7264bd1f6845036b0d9388.json',
 'a80b571df27c0987705a0faf8d8468bb.json',
 '105a4f2683bc462cac341e7edf56cb03.json',
 '4b0dd3b55db88e4708cb196f4f77408c.json',
 '69e25938850e71425bdca11d12e19c60.json',
 '3609aed4a265b4085842ac4a02bd675a.json',
 '97dbcbfe89da17d7be3ea2cf3367c33f.json',
 'edf668985c17edae1853f3d344819165.json',
 '9a10f2fc432232be8153bb38c04f77b7.json',
 '7d1513aa724b9869774eefe09208fd31.json',
 '937ad57ceb554fb1de7c55786199bc8b.json',
 'c011eb273bafef1484e915fcf1f0cf5b.json',
 'd38687e1190053bf9b40b652c7e4c614.json',
 '270de0e463123418934e30e042b9e7f1.json',
 '11fd6bbb0df5ab8f6a5a817cdfee4c7f.json',
 '66e1eb035ebea7328bc5aa50f6de7487.json',
 'e3490775af93cfe0ca8b67007fd8e70f.json',
 'a9a20bf3657c75ee1c49d7f2003ebd7c.json',
 '29cbf74bbbe64b87970d6e9dd22a997f.json',
 '3bff0de6ea54c9ceb0c4454dfc5e9abe.json',
 'd22dd70680dd06697bc74ca4926c49de.json',
 '32f28d74207d11e9b33711d0097789ad.json',
 'd48b4f0c1c1ecf53e8d04c8e63e92744.json',
 '4316f6d9868b6b37ccb8babd911f9cdf.json',
 'ed84c58ce897c9df9b7ebe4d62c2ca21.json',
 'b226a17e52e1573253a1e3607f437ac1.json',
 '13344fb7eae63e7f2c97de0a10544bae.json',
 '622872ae8a7123bc17b6347368febb92.json',
 '235b47290cca27fc81860e470483118d.json',
 'a28d7ab4d58858e3f40a53e53ff27d0f.json',
 '7f5a203fd8f9634696465fb7bad94c47.json',
 '6a4f4c4a66d02de48a7fdd6db68415a7.json',
 '918b89367a5a37119eb748c27a0d5507.json',
 'ee114af92ec1e8be369cb3808b5cb0d4.json',
 'b8bbde626883a443c78c136870f27c77.json',
 '9d33d13837a3d9bb4f7c3c4f4776ff88.json',
 '49ddab4c0ad8cd6e3e5cc03049178075.json',
 'a038de178594dc801bb9dff3604eb47c.json',
 'dae8c42cd0d46277b7e062efe154cd50.json',
 'edf293e97d65793e50ec38f52d367ddc.json',
 '8d1ba670c4e2a51ff5131a79051d17ee.json',
 '46455ab7d581d897ad30e0d7123a21e2.json',
 '9dd6d33017a0236d0c1be4e4c8298e28.json',
 'a9a5ca58af94263cc8c39d80cd22fb88.json',
 '3f4fd8da60794d0d78755af8185e8398.json',
 'b98d4f194ae4f43f803c2f841b5865b0.json',
 'cd5aba2071864cbb61950c7f735c2cdc.json',
 '6103cf2ef55c7258208455a39e4097ff.json',
 '45195bbfae5097b51bb544e7d2713a37.json',
 '4a4343440581e2e07902951ef3092e0c.json',
 '2f393e42211b02472543bfb8d6a51fa6.json',
 'c95c59388d87ba47fc04a6459d7ed226.json',
 '3672f985f84a610ce02d890e3e3b75dd.json',
 '8caf399cc6a057a3a1739192ebc4e300.json',
 'd5cf181762ff1187182b7751f1fc8bb0.json',
 'cb3445e1a1eb96ecc436f7975a4ef611.json',
 '9ae4c7497070632518629f5b4a83ad5f.json',
 'b0d598e395c889fee78ac7f14f3390c9.json',
 '5ee1fbcd1e46cc2c2e399e11711a6f91.json',
 '739d1b9e5486b20eaca35b29dd416fce.json',
 'cbe08a31747d05380c87450a19211213.json',
 'e6fa9465d10483fde7f6fae7d8b9a977.json',
 '5c4d8728ca01208aac9caff1df290299.json',
 'de65e4dc27ecf5a2fc2cbcd19090ea75.json',
 '39f6a8914bb2f504c03ac5a90097cf6d.json',
 '1f658d952202fedcdafb44f9843f7677.json',
 'f791e0fb0c19ad01d44c7ce79a7e40e9.json',
 '58e3a7b20a64e5d59d51702bea9a1ddd.json',
 'acb05aaccc3cfaaee486230f73e752db.json',
 '56155293db4866f8b9d3ded76bd75f91.json',
 'e39694b117c2d24eb8e3822eb93e3691.json',
 'd9978b9771dd1b9c9213a755470c9ca3.json',
 'ced98a839305662f6596aa1706473488.json',
 '48ce92f4ee7586eee88ef5cc3ae71e1c.json',
 '0f6473cade97202cd6a9329f80997940.json',
 '8ff5412f6549ebfe56ab9bcd00c681b1.json',
 '5b612f33182b5560788eabb6437905f1.json',
 'beaa4f1b77d8b006b259666bef477541.json',
 '75648bf9ed2330fcc6411b7f963c838f.json',
 '56edd2de9c3636fe6a89021a4ccd4d5d.json',
 '13d670b39cdb4f7e516f9a796dab50de.json',
 'bc43c911ca627f7a821fc0775c753f01.json',
 '4343383382492ff0feb0a1aa3413a687.json',
 '39b63196d3a1847118f4bb9d22107f03.json',
 '84bd722c7154d91ef8eed37b7add7c28.json',
 '6d40d638778960d9832432ba517be3e9.json',
 '0ba8a0c9c308b74bf61d354c937029a6.json',
 'c08d0c4c150ae7f0bbbadf278cf40109.json',
 '352b7cc08d581c4056fdc0bf5ae44bf5.json',
 '56f9cd6b8d70a0001e4628440fd5855d.json',
 '9dc2d280df3a3d9a7ed7ad44f6f81f13.json',
 '448fed6054eef074108744e28ba5d0d5.json',
 'd5e6e2f13a9681181179b9a6ccd0c0ef.json',
 '937f3640b170fdf3c3768b6dc9b65dcd.json',
 '27f7b893731790c957e3b6249c071799.json',
 'f439e3d1b474258af00eb41a072f7cd0.json',
 'a17199bb92e2d595891f5d5c9dba344d.json',
 'db92134c05b2b1cb445ebfee4b3caf09.json',
 'b1c11c47eb30da8c4d0cf15b74389a54.json',
 'c3787fa782dc9f197605ab8b2972a5f4.json',
 '7846eead86f78cabc99a1e4e032ad59c.json',
 '79266f02e3acc4889bceda9a0b99ccf5.json',
 'e7096c2a4beb6bdcecee4416c8515ad0.json',
 '7225544687ed4041d5e781e64fd4ae53.json',
 'fb5c934f68fa0f2b2fdcb224e4e34070.json',
 '027fb1689107514fc69f0a8c0a1073ae.json',
 '6fcb8f002c09172e63c4d031b704f1f7.json',
 'deda1402c4bc2eb23ebf98c7791c9936.json',
 '70c6df0ea87f6dae32227a87926a145a.json',
 '9dd1a47ee87c463741c530287bed6707.json',
 '126a1d775eee29f539f3d5afd199c555.json',
 '51c3bb3732476e6e34ae3666563fa399.json',
 '296ee673b974c9321e3b8061f4edf369.json',
 'e8c4435a622b96d07a6cf3219724c1d7.json',
 'a2759cf8b460947b4411fc0a03fe5d50.json',
 '3185996fc08911420008aefd84cb43c5.json',

In [44]:
from tqdm import tqdm

In [45]:
rows = [pd.read_json(os.path.join(directory, f), orient="records") for f in tqdm(files_only)]

100%|██████████| 109153/109153 [02:16<00:00, 796.91it/s]

In [46]:
df = pd.concat(rows, ignore_index=True)
df.head()

,requestID,eventTime,loanID,modelID,values
0,e3a240b4df07f93529120274d2796a1a,2024-01-23 07:31:59.995000,CC20240123a5a1,pd-cc-online,0.059997
1,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.165725
2,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.190000
3,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.068626
4,1122e55e8329f0d1446f38a9c34063e8,2024-02-09 15:19:56.487000,MORTGAGE20240209810e,pd-mortgage-online,0.150394

In [47]:
df.shape

(212569, 5)

In [68]:
import json

In [48]:
df = df[df.modelID == "pd-auto-online"]

In [49]:
df.head()

,requestID,eventTime,loanID,modelID,values
1,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.165725
2,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.190000
3,e04f78df44364892aa2c58634b09c837,2024-06-08 05:36:40.410000,CAR202406082d96,pd-auto-online,0.068626
9,e918d6bc8ecdbe93f8e952618a5f04f5,2024-06-24 08:53:54.812000,CAR202406249813,pd-auto-online,0.202490
10,e918d6bc8ecdbe93f8e952618a5f04f5,2024-06-24 08:53:54.812000,CAR202406249813,pd-auto-online,0.210000

In [50]:
df_help = pd.read_parquet("target.pq", engine="pyarrow")
df_help.head()

           loan_id period_start_date period_end_date
0  CAR202404241bd6        2024-10-27      2024-11-09
1  CAR20240111130f        2024-03-11      2024-05-04
2  CAR20240111130f        2024-07-16      2024-09-13
3  CAR20240111130f        2024-12-07      2025-02-01
4  CAR2024042453fd        2024-07-10      2024-09-06

In [55]:
df.shape

(155124, 5)

In [52]:
df.columns

Index(['requestID', 'eventTime', 'loanID', 'modelID', 'values'], dtype='object')

In [53]:
df_help.shape

(11129, 3)

In [57]:
print(df["loanID"].dtype)
print(df_help["loan_id"].dtype)

object
object

In [60]:
df["loanID"] = df["loanID"].astype(str)
df_help["loan_id"] = df_help["loan_id"].astype(str)

In [61]:
df_help.columns = ["loanID", "period_start_date", "period_end_date"]
df1 = pd.merge(
    left = df,
    right= df_help,
    on = "loanID",
    how = "inner"
)

In [62]:
df1.head()

,requestID,eventTime,loanID,modelID,values,period_start_date,period_end_date
0,5aeb9946ee82f44c5a7e65250adbbcd3,2024-03-01 17:52:39.547000,CAR2024030197af,pd-auto-online,0.038591,2024-11-23,2024-12-10
1,5aeb9946ee82f44c5a7e65250adbbcd3,2024-03-01 17:52:39.547000,CAR2024030197af,pd-auto-online,0.040000,2024-11-23,2024-12-10
2,5aeb9946ee82f44c5a7e65250adbbcd3,2024-03-01 17:52:39.547000,CAR2024030197af,pd-auto-online,0.032955,2024-11-23,2024-12-10
3,adaabcdb47dfc21bf5d49b28762f0398,2024-03-30 05:29:56.463000,CAR20240330a822,pd-auto-online,0.046567,2024-12-01,2024-12-15
4,adaabcdb47dfc21bf5d49b28762f0398,2024-03-30 05:29:56.463000,CAR20240330a822,pd-auto-online,0.010000,2024-12-01,2024-12-15

In [63]:
df.loanID.unique()

array(['CAR202406082d96', 'CAR202406249813', 'CAR2024020807ff', ...,
       'CAR202404294b86', 'CAR2024050622fb', 'CAR202402169701'],
      shape=(51708,), dtype=object)

In [64]:
df_help.loanID.unique()

array(['CAR202404241bd6', 'CAR20240111130f', 'CAR2024042453fd', ...,
       'CAR2024041828dd', 'CAR202404183d8a', 'CAR202405121054'],
      shape=(8063,), dtype=object)

In [65]:
set(df["loanID"]).intersection(set(df_help["loanID"]))

{'CAR202403100537',
 'CAR202401216cd9',
 'CAR202406134871',
 'CAR20240207978f',
 'CAR202405025a79',
 'CAR2024052912e5',
 'CAR202403168834',
 'CAR202401089a0e',
 'CAR202401084042',
 'CAR20240309ef92',
 'CAR2024042524aa',
 'CAR202403184edb',
 'CAR202402138963',
 'CAR202401027d57',
 'CAR20240619cb7c',
 'CAR20240210ff7d',
 'CAR20240514dba1',
 'CAR20240522806a',
 'CAR202403257ef6',
 'CAR20240525421b',
 'CAR202404262817',
 'CAR202404042d3a',
 'CAR20240526ac8a',
 'CAR2024041129a9',
 'CAR20240219b68c',
 'CAR2024050891c7',
 'CAR2024012736ad',
 'CAR202405243f5e',
 'CAR20240307f8da',
 'CAR202404074f28',
 'CAR202401055938',
 'CAR20240202430c',
 'CAR20240328b440',
 'CAR202405111725',
 'CAR2024020648df',
 'CAR20240220d863',
 'CAR20240529db29',
 'CAR202406032352',
 'CAR202404175a2a',
 'CAR2024061484f5',
 'CAR2024051058d4',
 'CAR202406237dc8',
 'CAR202402199166',
 'CAR2024022292b7',
 'CAR202405143210',
 'CAR20240629f7b6',
 'CAR202401231ff8',
 'CAR20240223de70',
 'CAR202406189446',
 'CAR20240203e531',
 'CAR20240127a816',
 'CAR202403145650',
 'CAR20240102fa40',
 'CAR20240105baea',
 'CAR202403051b69',
 'CAR20240126ddac',
 'CAR202404259f1f',
 'CAR202404039ba1',
 'CAR20240414288c',
 'CAR20240216e165',
 'CAR20240607bc37',
 'CAR20240508d4b5',
 'CAR202406216e92',
 'CAR20240112a753',
 'CAR20240602c646',
 'CAR202401199c22',
 'CAR20240603973a',
 'CAR20240302350a',
 'CAR202401192348',
 'CAR20240317e5b2',
 'CAR202406194d95',
 'CAR20240529afab',
 'CAR2024041703b2',
 'CAR20240612803e',
 'CAR20240623afb0',
 'CAR20240326076c',
 'CAR20240408f2b5',
 'CAR2024022347fd',
 'CAR202406210aa1',
 'CAR20240317f953',
 'CAR202401048d6d',
 'CAR202403232576',
 'CAR2024032428e2',
 'CAR20240107cc91',
 'CAR20240210b035',
 'CAR20240513700a',
 'CAR20240405d903',
 'CAR202405023202',
 'CAR20240501889f',
 'CAR20240110976a',
 'CAR2024053122ac',
 'CAR20240219d2a2',
 'CAR202406043332',
 'CAR202406282bdf',
 'CAR202405061c38',
 'CAR2024052477f9',
 'CAR20240228335f',
 'CAR2024030695e1',
 'CAR202402123b50',
 'CAR2024012144bf',
 'CAR202401129357',
 'CAR202406151ef0',
 'CAR202404206271',
 'CAR20240525b5a1',
 'CAR20240203ff1d',
 'CAR20240124ea50',
 'CAR20240130ebc0',
 'CAR202401202be9',
 'CAR202405100a2a',
 'CAR20240127e5e5',
 'CAR2024042984e8',
 'CAR202406082548',
 'CAR20240308818c',
 'CAR202403258ab8',
 'CAR20240116609e',
 'CAR20240623a586',
 'CAR20240310f7da',
 'CAR2024012637a7',
 'CAR20240317d045',
 'CAR2024062865cf',
 'CAR202402186df1',
 'CAR2024041414ad',
 'CAR2024012941c5',
 'CAR20240301e32c',
 'CAR20240408547b',
 'CAR20240414a42b',
 'CAR20240604a5a6',
 'CAR20240227e992',
 'CAR2024030292c8',
 'CAR202404145131',
 'CAR202403215913',
 'CAR202402161d08',
 'CAR20240502fd9d',
 'CAR2024021563cb',
 'CAR2024020163f4',
 'CAR20240509f250',
 'CAR2024061431fe',
 'CAR202405140ebc',
 'CAR20240609b22e',
 'CAR2024062639dc',
 'CAR202403248fec',
 'CAR202402259ec5',
 'CAR20240630749c',
 'CAR20240131be6c',
 'CAR20240609cfc5',
 'CAR20240324b448',
 'CAR202402110228',
 'CAR202403052557',
 'CAR202403310e1e',
 'CAR20240610d254',
 'CAR202404067dd0',
 'CAR202403126b62',
 'CAR202404110def',
 'CAR202404247857',
 'CAR202404162ba8',
 'CAR2024041612e3',
 'CAR20240504288c',
 'CAR20240418d5ce',
 'CAR20240510fd34',
 'CAR202404257502',
 'CAR20240203cf2e',
 'CAR2024011333bb',
 'CAR202402278c7b',
 'CAR20240608927e',
 'CAR20240429c666',
 'CAR20240308a060',
 'CAR20240223ef41',
 'CAR202404271cec',
 'CAR202403271b62',
 'CAR20240220cf67',
 'CAR2024020699ef',
 'CAR202402024be5',
 'CAR20240504217f',
 'CAR202406066194',
 'CAR20240303b32e',
 'CAR20240122e702',
 'CAR20240608f569',
 'CAR20240503bb79',
 'CAR20240327fdad',
 'CAR2024050139cd',
 'CAR20240507ced9',
 'CAR202406247bd2',
 'CAR2024052683ad',
 'CAR20240103b04c',
 'CAR202404242a9d',
 'CAR20240206219e',
 'CAR20240223405e',
 'CAR20240603c5d2',
 'CAR20240401cfec',
 'CAR20240223656c',
 'CAR202404094a2d',
 'CAR20240413096d',
 'CAR202402079d68',
 'CAR2024040261bf',
 'CAR20240603ddd1',
 'CAR202405165cce',
 'CAR202406071695',
 'CAR20240403e49e',
 'CAR202405152c27',
 'CAR2024062843fa',
 'CAR202402237cfd',
 'CAR202402191cc8',
 'CAR202403063fe2',
 'CAR20240318bd22',
 'CAR202403083980',
 'CAR202401229001',
 'CAR202404088b57',
 'CAR202405163567',
 'CAR20240125e6d8',
 'CAR202402219724',
 'CAR202405287813',
 'CAR20240312fa83',
 'CAR2024040265f1',
 'CAR202401064a11',
 'CAR202404259d74',
 'CAR20240621ba9f',
 'CAR202404173185',
 'CAR2024022617a3',
 'CAR202402105e9d',
 'CAR202402120bb4',
 'CAR202403158289',
 'CAR202402075dbc',
 'CAR20240520b670',
 'CAR20240403274a',
 'CAR20240219ed0e',
 'CAR20240520a1d3',
 'CAR202403140e9d',
 'CAR202403180db2',
 'CAR202405172fd0',
 'CAR20240419a223',
 'CAR202406187012',
 'CAR202401252c75',
 'CAR2024042681ca',
 'CAR20240325b0ab',
 'CAR2024032421b5',
 'CAR20240229de96',
 'CAR202402219773',
 'CAR20240130128a',
 'CAR20240502da64',
 'CAR20240108eea5',
 'CAR20240308a588',
 'CAR20240108ef7b',
 'CAR202406306fbd',
 'CAR20240203f9fd',
 'CAR202406024b0a',
 'CAR202403236805',
 'CAR20240529139f',
 'CAR20240215ac64',
 'CAR20240221c730',
 'CAR202405070b9e',
 'CAR202402135d4a',
 'CAR2024042453fd',
 'CAR20240224dca5',
 'CAR202403033636',
 'CAR20240620258b',
 'CAR2024051273c0',
 'CAR202402182b45',
 'CAR202404197cc5',
 'CAR202405102012',
 'CAR20240125ea4e',
 'CAR202401281600',
 'CAR2024032371c1',
 'CAR20240225b028',
 'CAR20240503aeef',
 'CAR202406110141',
 'CAR20240523dae3',
 'CAR20240619c0c7',
 'CAR2024010720f7',
 'CAR20240303fead',
 'CAR202402012352',
 'CAR20240106e8fd',
 'CAR20240314d575',
 'CAR20240506d1f2',
 'CAR20240129c10f',
 'CAR202402228dd4',
 'CAR20240220b085',
 'CAR20240321d9d3',
 'CAR202401133a82',
 'CAR20240501a461',
 'CAR202404062056',
 'CAR2024040368a1',
 'CAR202402271dc3',
 'CAR202405121732',
 'CAR202401316f3a',
 'CAR202405181b32',
 'CAR20240113e8c0',
 'CAR20240121c3a6',
 'CAR20240221cf9b',
 'CAR20240610e2ea',
 'CAR20240406319a',
 'CAR20240510ecb9',
 'CAR202401180d77',
 'CAR202403149dee',
 'CAR20240615f8d2',
 'CAR202406252c60',
 'CAR2024010461c6',
 'CAR20240411fe04',
 'CAR202402020166',
 'CAR202401184150',
 'CAR20240416cdda',
 'CAR202403290ff3',
 'CAR202401015f0a',
 'CAR2024041554fe',
 'CAR20240504d361',
 'CAR2024012401e0',
 'CAR20240126f542',
 'CAR202405091177',
 'CAR20240513c447',
 'CAR202405031359',
 'CAR20240205bac4',
 'CAR20240426fba9',
 'CAR20240225f52b',
 'CAR20240622d606',
 'CAR20240326a8ec',
 'CAR2024062605b2',
 'CAR202403190b08',
 'CAR20240309b837',
 'CAR202405039f4e',
 'CAR20240216c450',
 'CAR20240131c236',
 'CAR20240403362c',
 'CAR20240227c570',
 'CAR202403164b5b',
 'CAR20240628566f',
 'CAR202401200614',
 'CAR20240301d7fd',
 'CAR2024020672b3',
 'CAR202405017733',
 'CAR20240425803a',
 'CAR202406092504',
 'CAR20240613329e',
 'CAR20240218c1fe',
 'CAR202405028a0c',
 'CAR2024041135bf',
 'CAR20240106da0d',
 'CAR20240105b7d3',
 'CAR202404033d38',
 'CAR202402178fc6',
 'CAR20240129a3d0',
 'CAR20240319348a',
 'CAR2024051769da',
 'CAR202406027f36',
 'CAR202401106f16',
 'CAR202406251458',
 'CAR20240605fb7b',
 'CAR2024010958a2',
 'CAR202403015acd',
 'CAR2024021458d2',
 'CAR2024021817b6',
 'CAR2024062932b6',
 'CAR20240510b3b4',
 'CAR202406087bcd',
 'CAR20240207a821',
 'CAR202404265d0c',
 'CAR20240626b0d3',
 'CAR2024012602d7',
 'CAR20240521eaa5',
 'CAR20240210c7af',
 'CAR20240420f1de',
 'CAR20240328c10f',
 'CAR202403224138',
 'CAR202403115913',
 'CAR20240504e0ec',
 'CAR202403272049',
 'CAR202406173569',
 'CAR202404188c5f',
 'CAR202404109431',
 'CAR20240526c76d',
 'CAR20240521b740',
 'CAR2024061358a2',
 'CAR2024051262e7',
 'CAR202404193ff3',
 'CAR20240329e068',
 'CAR20240419d645',
 'CAR20240213f5e5',
 'CAR202402127587',
 'CAR20240327fbb1',
 'CAR202403135cb2',
 'CAR20240203868b',
 'CAR20240103d005',
 'CAR20240321b265',
 'CAR20240221a2fe',
 'CAR202404275af1',
 'CAR20240417d7f1',
 'CAR202405152435',
 'CAR2024031858b4',
 'CAR20240113b090',
 'CAR202402182517',
 'CAR202402241a67',
 'CAR20240423d240',
 'CAR202405241340',
 'CAR20240402a5e0',
 'CAR202401183561',
 'CAR202406175055',
 'CAR202401242c8e',
 'CAR20240313746b',
 'CAR20240114c3e4',
 'CAR202404010756',
 'CAR20240109174f',
 'CAR202405316e7d',
 'CAR20240627bb4a',
 'CAR202402098091',
 'CAR202406211049',
 'CAR202403311a68',
 'CAR202404014042',
 'CAR20240229679d',
 'CAR20240111f39a',
 'CAR202403037288',
 'CAR20240615626f',
 'CAR202403085eed',
 'CAR20240415a6e8',
 'CAR202404198133',
 'CAR20240327219c',
 'CAR20240616c381',
 'CAR20240511aee9',
 'CAR202405293001',
 'CAR20240109fd5c',
 'CAR202401269393',
 'CAR20240204573f',
 'CAR202401236a58',
 'CAR202401319cea',
 'CAR202401070d85',
 'CAR2024011849ad',
 'CAR20240320966e',
 'CAR20240624fd5a',
 'CAR20240122a9cc',
 'CAR20240109b45f',
 'CAR202406053bd4',
 'CAR20240629b8ce',
 'CAR20240106ada5',
 'CAR20240323a5bf',
 'CAR20240404e843',
 'CAR202403136f5e',
 'CAR202406015131',
 'CAR20240629eebe',
 'CAR202404093a9d',
 'CAR20240325c7af',
 'CAR20240628504b',
 'CAR2024051900a2',
 'CAR20240108d4b5',
 'CAR20240526878a',
 'CAR2024021898f1',
 'CAR20240116dbb2',
 'CAR20240630d1dc',
 'CAR202405179308',
 'CAR20240622d1dc',
 'CAR20240525d4ec',
 'CAR202404110000',
 'CAR202405242dea',
 'CAR202401039ec5',
 'CAR202404069f53',
 'CAR202406023f43',
 'CAR20240626d503',
 'CAR202401250cd6',
 'CAR202401241fc2',
 'CAR20240130a64b',
 'CAR202405299d27',
 'CAR2024051241d8',
 'CAR20240307cd50',
 'CAR20240403e7e6',
 'CAR202401174b85',
 'CAR20240221f3f1',
 'CAR202401028ca0',
 'CAR20240211182e',
 'CAR2024031642a8',
 'CAR202403314c14',
 'CAR202406146e31',
 'CAR202401082a8a',
 'CAR20240215f786',
 'CAR202403279fb7',
 'CAR20240130455c',
 'CAR2024022389fc',
 'CAR20240214e769',
 'CAR20240602eb16',
 'CAR20240620f1b0',
 'CAR202403094a30',
 'CAR202405136377',
 'CAR20240501a609',
 'CAR202405020a54',
 'CAR202401261f50',
 'CAR20240125311a',
 'CAR2024062190db',
 'CAR20240625a749',
 'CAR2024040512fb',
 'CAR202403114d70',
 'CAR20240120331c',
 'CAR202401053a1d',
 'CAR202403100496',
 'CAR202406017793',
 'CAR202405138d33',
 'CAR202405094db0',
 'CAR202403286422',
 'CAR20240419411a',
 'CAR20240113cf2f',
 'CAR20240314a36b',
 'CAR20240108dc6a',
 'CAR2024011894c4',
 'CAR20240624e16e',
 'CAR20240421116c',
 'CAR202405197dc8',
 'CAR20240414d198',
 'CAR202403077e6b',
 'CAR20240118b661',
 'CAR202406292250',
 'CAR202405260996',
 'CAR20240521ab73',
 'CAR202404018aec',
 'CAR202406238ca8',
 'CAR20240120a7eb',
 'CAR20240521e148',
 'CAR20240207fb3f',
 'CAR202406185fd5',
 'CAR2024060854f3',
 'CAR2024060999cd',
 'CAR20240415f4dd',
 'CAR202401306cf8',
 'CAR202401224abe',
 'CAR20240413f50a',
 'CAR202401267d60',
 'CAR20240413cd75',
 'CAR2024022945fb',
 'CAR20240316f90f',
 'CAR20240203dfb8',
 'CAR20240224b5ec',
 'CAR20240124931a',
 'CAR202404023e52',
 'CAR202401177374',
 'CAR2024052883a3',
 'CAR202404270ac6',
 'CAR2024052511bc',
 'CAR20240418e6e9',
 'CAR20240423f858',
 'CAR202401159bc9',
 'CAR2024020398ba',
 'CAR20240614f7da',
 'CAR202402071438',
 'CAR20240124d045',
 'CAR20240105779e',
 'CAR202401022e9f',
 'CAR202402078f91',
 'CAR202403097ac5',
 'CAR20240525dea9',
 'CAR202402080cdb',
 'CAR202405264415',
 'CAR202404226332',
 'CAR202402139f65',
 'CAR20240430de53',
 'CAR2024061398ed',
 'CAR202406220ef0',
 'CAR202404122b45',
 'CAR202401157eb3',
 'CAR2024060573f4',
 'CAR20240428f81e',
 'CAR20240518bcc2',
 'CAR202403063fe7',
 'CAR20240629f04b',
 'CAR20240305ccf0',
 'CAR202404099565',
 'CAR202406098f04',
 'CAR20240508a8f8',
 'CAR2024041435d0',
 'CAR20240531a8ac',
 'CAR202405088e44',
 'CAR20240114598a',
 'CAR202401077cac',
 'CAR2024040584d5',
 'CAR202404185129',
 'CAR202402287171',
 'CAR20240416d67d',
 'CAR202405253ba9',
 'CAR20240201aff0',
 'CAR2024042082e6',
 'CAR202402259d05',
 'CAR202401050004',
 'CAR20240427d921',
 'CAR20240627d902',
 'CAR20240329e17a',
 'CAR202405140d73',
 'CAR202405093ec2',
 'CAR20240327ad8e',
 'CAR202405247bc1',
 'CAR202401130b40',
 'CAR202406309922',
 'CAR2024040294f4',
 'CAR20240528464d',
 'CAR20240517a422',
 'CAR20240510c4bf',
 'CAR20240430102b',
 'CAR202404135c8e',
 'CAR20240315c7af',
 'CAR20240123f50a',
 'CAR202405088d1d',
 'CAR202402233f5e',
 'CAR20240108b4a5',
 'CAR202405020b7e',
 'CAR20240225f29c',
 'CAR202401111e59',
 'CAR20240221a36b',
 'CAR20240607ad55',
 'CAR202404263def',
 'CAR20240322e569',
 'CAR202405257d12',
 'CAR20240118b19d',
 'CAR20240629acd9',
 'CAR20240418f0ea',
 'CAR202406174b2e',
 'CAR202404297967',
 'CAR2024050160c9',
 'CAR20240312de8a',
 'CAR202404108f04',
 'CAR20240315322f',
 'CAR2024041691e8',
 'CAR202404241fa6',
 'CAR20240628448d',
 'CAR20240321f461',
 'CAR202403203c09',
 'CAR20240630606c',
 'CAR2024041529a9',
 'CAR202401275f0f',
 'CAR20240207859b',
 'CAR20240414eaa1',
 'CAR202401319896',
 'CAR202404150a2a',
 'CAR202406171305',
 'CAR20240122d380',
 'CAR20240619e82c',
 'CAR20240614b463',
 'CAR20240202edcd',
 'CAR20240514ee80',
 'CAR202401145607',
 'CAR202406214e09',
 'CAR20240221bce9',
 'CAR202405223083',
 'CAR20240201d554',
 'CAR20240610eeae',
 'CAR202403027793',
 'CAR2024050880a1',
 'CAR202402221769',
 'CAR20240620ca3a',
 'CAR20240330a51f',
 'CAR202401274397',
 'CAR202406263676',
 'CAR202401030e2d',
 'CAR202402196f78',
 'CAR20240528d840',
 'CAR202402220234',
 'CAR20240307069d',
 'CAR20240618c535',
 'CAR20240110c74c',
 'CAR20240503f55c',
 'CAR2024042630ef',
 'CAR20240416a5b9',
 'CAR202402067d3e',
 'CAR20240117dd45',
 'CAR202404212953',
 'CAR202404157b67',
 'CAR202404247177',
 'CAR2024052897af',
 'CAR20240625d800',
 'CAR2024010425ca',
 'CAR20240416f3f1',
 'CAR20240420bd9e',
 'CAR202404134921',
 'CAR20240402c74c',
 'CAR20240416c89e',
 'CAR2024022162da',
 'CAR202401031c33',
 'CAR20240227fe1f',
 'CAR202403207180',
 'CAR20240122dba1',
 'CAR20240219fc03',
 'CAR2024021903a3',
 'CAR2024041312b6',
 'CAR20240114cc59',
 'CAR2024061053c3',
 'CAR20240529258e',
 'CAR20240307ba82',
 'CAR20240113ec08',
 'CAR20240201099f',
 'CAR20240629f1a9',
 'CAR202406208725',
 'CAR2024031154ee',
 'CAR20240211421b',
 'CAR202406137734',
 'CAR20240330d6c6',
 'CAR202405091808',
 'CAR20240223e910',
 'CAR202403086fc3',
 'CAR202401109559',
 'CAR20240606670c',
 'CAR20240629e362',
 'CAR20240426d1e9',
 'CAR20240119e419',
 'CAR2024011546a5',
 'CAR2024012084cb',
 'CAR20240426b356',
 'CAR202403263948',
 'CAR202402034b04',
 'CAR20240522baea',
 'CAR2024012701e9',
 'CAR2024011504df',
 'CAR20240611f890',
 'CAR20240322b44a',
 'CAR20240224abe8',
 'CAR202405251cb5',
 'CAR202405309a1d',
 'CAR202404117786',
 'CAR202401046ffa',
 'CAR202405275ca3',
 'CAR202403236d70',
 'CAR20240222cda7',
 'CAR20240509161f',
 'CAR202405218b3b',
 'CAR2024041870a3',
 'CAR20240106f0f6',
 'CAR202406130328',
 'CAR20240219754d',
 'CAR202402088369',
 'CAR202403158a71',
 'CAR20240611c61f',
 'CAR202406300950',
 'CAR202401197938',
 'CAR20240115859b',
 'CAR20240128f4f6',
 'CAR2024020584d9',
 'CAR2024042894b5',
 'CAR202401102e3a',
 'CAR20240414a1a6',
 'CAR20240522362c',
 'CAR20240430698d',
 'CAR2024051009cc',
 'CAR2024062364ee',
 'CAR20240531f05f',
 'CAR202406109238',
 'CAR20240214eecc',
 'CAR202405043ffe',
 'CAR20240120abcc',
 'CAR20240513e979',
 'CAR202403251f5f',
 'CAR20240128a501',
 'CAR20240225be53',
 'CAR202406174fa9',
 'CAR202402113df8',
 'CAR2024050813d6',
 'CAR20240317cd50',
 'CAR20240203dca4',
 'CAR20240520b8c2',
 'CAR2024062783dd',
 'CAR2024050933a5',
 'CAR20240304c4bf',
 'CAR20240511ef0b',
 'CAR20240320993e',
 'CAR20240129c315',
 'CAR20240630e0cd',
 'CAR202401308558',
 'CAR202403057c78',
 'CAR20240325e3bc',
 'CAR202401209426',
 'CAR20240119d042',
 'CAR20240622808e',
 'CAR202405186e09',
 'CAR2024030502ed',
 'CAR2024032432b9',
 'CAR2024030981c8',
 'CAR20240321315b',
 'CAR20240330ac2a',
 'CAR20240429995f',
 'CAR2024031549c1',
 'CAR2024051728f7',
 'CAR20240305b0b1',
 'CAR202403296d37',
 'CAR20240117c157',
 'CAR20240518b8c3',
 'CAR202403030690',
 'CAR202401057421',
 'CAR202403301cf2',
 'CAR202404146c2f',
 'CAR20240311ac00',
 'CAR20240306cacb',
 'CAR20240519e8b1',
 'CAR20240311d58f',
 'CAR202401270e67',
 'CAR20240415f2c3',
 'CAR202405173bd7',
 'CAR202403079c77',
 'CAR202404030332',
 'CAR2024060917ed',
 'CAR20240418e9da',
 'CAR20240323b056',
 'CAR2024021069cd',
 'CAR202403227900',
 'CAR202405216978',
 'CAR20240228f542',
 'CAR202401147857',
 'CAR2024040993da',
 'CAR20240623d550',
 'CAR20240131923e',
 'CAR202406268283',
 'CAR202406120b0b',
 'CAR202403089e82',
 'CAR202403172bce',
 'CAR202403294cef',
 'CAR202402062ba3',
 'CAR202404104c5b',
 'CAR202405256591',
 'CAR202402148c00',
 'CAR2024042851be',
 'CAR202403123bf0',
 'CAR202403109afe',
 'CAR202401070e4c',
 'CAR20240202c6d4',
 'CAR202402120f34',
 'CAR20240319bc27',
 'CAR20240401d165',
 'CAR202404088c6d',
 'CAR20240506ce47',
 'CAR202406093c1e',
 'CAR2024031003e7',
 'CAR20240228cf04',
 'CAR202406051a34',
 'CAR20240327bd13',
 'CAR2024031704b0',
 'CAR202404039327',
 'CAR20240224028e',
 'CAR20240601654a',
 'CAR202402057912',
 'CAR20240126a060',
 'CAR20240122eb6d',
 'CAR20240430ed1d',
 'CAR2024010955ed',
 'CAR20240412dc87',
 'CAR202403200d85',
 'CAR20240401a2fe',
 'CAR202406064249',
 'CAR202401221482',
 'CAR20240514443c',
 'CAR20240601d8ab',
 'CAR2024031917eb',
 'CAR20240117fd4c',
 'CAR20240522f0fc',
 'CAR202402187146',
 'CAR20240225e085',
 'CAR20240113ac4e',
 'CAR202402111db3',
 'CAR202404066b8e',
 'CAR20240228dc04',
 'CAR2024033090ae',
 'CAR202406157eb5',
 'CAR2024060887ae',
 'CAR202401224cf0',
 'CAR2024022094f6',
 'CAR202401261006',
 'CAR202401275e72',
 'CAR202402018efb',
 'CAR20240103342c',
 'CAR2024050448e5',
 'CAR20240628440e',
 'CAR202404213413',
 'CAR202405279570',
 'CAR202402182227',
 'CAR20240308f925',
 'CAR202402086e62',
 'CAR202404025650',
 'CAR20240402f64e',
 'CAR20240206443d',
 'CAR20240614d4df',
 'CAR202403155c34',
 'CAR202405196e61',
 'CAR20240108b331',
 'CAR20240206f2b9',
 'CAR20240317cab0',
 'CAR202404094c07',
 'CAR20240112735b',
 'CAR20240521f26b',
 'CAR202402195f04',
 'CAR20240512d93e',
 'CAR202406242758',
 'CAR2024041595d3',
 'CAR202401211145',
 'CAR202405055df0',
 'CAR2024011885f3',
 'CAR20240210a004',
 'CAR20240110df0a',
 'CAR202405288ef9',
 'CAR202404264e87',
 'CAR2024020868d3',
 'CAR20240312fbd3',
 'CAR20240521609c',
 'CAR20240324b2ab',
 'CAR20240317e37b',
 'CAR20240110fa8d',
 'CAR20240119b083',
 'CAR20240113d56b',
 'CAR202403172639',
 'CAR202401177e6f',
 'CAR2024031166f8',
 'CAR20240425e8aa',
 'CAR20240103d04c',
 'CAR20240327c7b0',
 'CAR202404165dd3',
 'CAR20240624373e',
 'CAR202406035d61',
 'CAR2024060917d8',
 'CAR202403135a9d',
 'CAR202405110e01',
 'CAR20240505fcdb',
 'CAR20240523fd2a',
 'CAR202402286734',
 'CAR202405077082',
 'CAR202406078ce6',
 'CAR20240331bb14',
 'CAR202401019183',
 'CAR202403054d70',
 'CAR202403086e42',
 'CAR202403022c79',
 'CAR2024061384b2',
 'CAR20240128b38e',
 'CAR2024063064f1',
 'CAR202404069cea',
 'CAR202403111977',
 'CAR2024032098f1',
 'CAR202404069b52',
 'CAR20240405b28d',
 'CAR20240113f4be',
 'CAR20240514770c',
 'CAR202403167274',
 'CAR20240213159c',
 'CAR20240518edc2',
 'CAR20240623721e',
 'CAR2024032205b0',
 'CAR2024032040cc',
 'CAR202401188805',
 'CAR202405097ec6',
 'CAR20240425fd8c',
 'CAR20240513767d',
 'CAR20240428a242',
 'CAR2024030289da',
 'CAR20240520838f',
 'CAR2024032974e1',
 'CAR20240215a3c7',
 'CAR20240620a428',
 'CAR20240120f068',
 'CAR20240207b6a8',
 'CAR2024011667ed',
 'CAR2024032159e0',
 'CAR20240121f14b',
 'CAR20240330ebb8',
 'CAR202404137553',
 'CAR20240518c441',
 'CAR20240529de92',
 'CAR202402082c04',
 'CAR202405319204',
 'CAR202401183ea2',
 'CAR2024052584c6',
 'CAR20240427fe9f',
 'CAR202401017022',
 'CAR202405229033',
 'CAR202402130c2a',
 'CAR202403100138',
 'CAR202406209365',
 'CAR20240517455c',
 'CAR20240103a44b',
 'CAR202405192056',
 'CAR20240311dc09',
 'CAR20240629cd6c',
 'CAR20240318dc6e',
 'CAR2024050830c8',
 'CAR2024032292ae',
 'CAR20240513fbd7',
 'CAR202405040c9e',
 'CAR202404169823',
 'CAR202404055487',
 'CAR20240125239f',
 'CAR20240226e804',
 'CAR202405030b33',
 'CAR20240619d863',
 'CAR20240212a3d0',
 'CAR202405257af6',
 'CAR202406015cf6',
 'CAR202406092e20',
 'CAR20240121489d',
 'CAR2024011099ba',
 'CAR20240323e3a5',
 'CAR202401172284',
 'CAR20240329ebb7',
 'CAR20240426e474',
 'CAR20240108838f',
 'CAR202405024a21',
 'CAR2024022525b0',
 'CAR2024042631a6',
 'CAR20240325084a',
 'CAR20240131705f',
 'CAR202404255c53',
 'CAR202406242d19',
 'CAR20240616e0be',
 'CAR20240610af5d',
 'CAR202405248d9f',
 'CAR20240125bc3c',
 'CAR202401135a79',
 'CAR20240522626f',

In [66]:
df1.shape

(33387, 7)

In [ ]:
df1.columns

Index(['requestID', 'eventTime', 'loanID', 'modelID', 'values',
       'period_start_date', 'period_end_date'],
      dtype='object')

In [76]:
df1['final_model_score'] = df1['values']

In [77]:
df2 = df1.copy()

In [78]:

df2 = df1.copy()


df2['eventTime'] = pd.to_datetime(df2['eventTime'])
df2['period_start_date'] = pd.to_datetime(df2['period_start_date'])
df2['period_end_date'] = pd.to_datetime(df2['period_end_date'])

df2['default_flag'] = ((df2['period_end_date'] - df2['eventTime']).dt.days <= 120) & ((df2['period_end_date'] - df2['period_start_date']).dt.days >= 30) 
df2['default_flag'] = df2['default_flag'].astype(int)

df2['month'] = df2['eventTime'].dt.to_period('M')

In [82]:
from sklearn.metrics import roc_auc_score

def gini_safe(y_true, y_score):
    mask = (~y_true.isna()) & (~y_score.isna())
    if mask.sum() == 0 or len(np.unique(y_true[mask])) == 1:
        return np.nan
    return 2 * roc_auc_score(y_true[mask], y_score[mask]) - 1

In [83]:
gini_monthly = df2.groupby('month').apply(
    lambda x: pd.Series({
        'gini_final': gini_safe(x['default_flag'], x['final_model_score'])
    })
).reset_index()

print(gini_monthly)

     month  gini_final
0  2024-01    0.198195
1  2024-02    0.235338
2  2024-03    0.198094
3  2024-04    0.202271
4  2024-05    0.219917
5  2024-06    0.193369

/var/folders/8g/hrr0dtn57lb04xhx37szq0k00000gn/T/ipykernel_42223/2571018819.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  gini_monthly = df2.groupby('month').apply(

In [84]:
def bootstrap_gini_safe(df_slice, n_iter=1000, sample_frac=0.7):
    df_slice = df_slice.dropna(subset=['final_model_score', 'default_flag'])
    if len(df_slice) == 0:
        return [np.nan, np.nan]
    gini_vals = []
    n = int(len(df_slice) * sample_frac)
    for _ in range(n_iter):
        sample = df_slice.sample(n=n, replace=True)
        gini_vals.append(gini_safe(sample['default_flag'], sample['final_model_score']))
    return np.percentile(gini_vals, [2.5, 97.5])

In [85]:
ci_monthly = df2.groupby('month').apply(
    lambda x: pd.Series(bootstrap_gini_safe(x, n_iter=1000, sample_frac=0.7),
                        index=['gini_ci_lower', 'gini_ci_upper'])
).reset_index()


gini_monthly = gini_monthly.merge(ci_monthly, on='month')
print(gini_monthly)

     month  gini_final  gini_ci_lower  gini_ci_upper
0  2024-01    0.198195       0.158359       0.241025
1  2024-02    0.235338       0.189640       0.280800
2  2024-03    0.198094       0.157704       0.241301
3  2024-04    0.202271       0.159383       0.245457
4  2024-05    0.219917       0.182275       0.261475
5  2024-06    0.193369       0.147178       0.240379

/var/folders/8g/hrr0dtn57lb04xhx37szq0k00000gn/T/ipykernel_42223/3742429609.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ci_monthly = df2.groupby('month').apply(

In [86]:
np.mean(gini_monthly.gini_final)

np.float64(0.20786404469456132)